version: "3.9"
services:
  smb_server:
    build: ./images/smb_server
    hostname: smb_server


  smb_client:
    build: ./images/smb_client
    ports:
      - "5000:22"
    hostname: smb_client
    # depends_on:
    #   - smb_server
    depends_on:
      - serviceName: smb_server
        condition: service_healthy
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH