version: "3.9"
services:
  ub_1:
    build: ./ubuntu_practice
    ports:
      - "8400:22"
      - "8401:80"
  ub_2:
    build: ./ubuntu_practice
    ports:
      - "8500:22"
      - "8501:80"
  fd_1:
    build: ./fedora_practice
    ports:
      - "9000:22"
    environment:
      SSH_USERPASS: password
  splunk:
    image: splunk/splunk:latest
    ports:
      - "8000:8000"
      - "9997:9997"
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: adminadmin